### ISSUE TITLE
Capitalize each line of output

### ISSUE THREAD

**Issue by zwigby** [XervoIO/ghost-buster#2]
Would be nice for the output to be consistent.

**Comment by tzmanics** [comment]
Hi @zwigby sorry for the big delay in response, we aren't currently maintaining this repo so I'm going to close this issue for now. Once we figure out the next steps for `ghost-buster` we'll post an update on the repo.

Thanks for reaching out and feel free to re-open this issue if it's something you would like addressed sooner rather than later.
