### ISSUE TITLE
Need to be able to set URL for blog.

### ISSUE THREAD

**Issue by zwigby** [XervoIO/ghost-buster#4]
It would be nice to be able to set the URL for the blog. This way I could just download ghost zip, run ghost-buster and push it for a new working blog.

**Comment by zwigby** [comment]
Ad a bare minimum should at least document what people should set in config.js to be ready to run in best scenario.

**Comment by tzmanics** [comment]
Hi again @zwigby :) sorry for the big delay in response, we aren't currently maintaining this repo so I'm going to close this issue for now. Once we figure out the next steps for ghost-buster we'll post an update on the repo.

Thanks for reaching out and feel free to re-open this issue if it's something you would like addressed sooner rather than later.
