### ISSUE TITLE
Image files lost during 'modulus deploy' with Ghost v0.4.0

### ISSUE THREAD

**Issue by BrianHoldsworth** [XervoIO/ghost-buster#5]
I upgraded my Ghost blog on Modulus to the new 0.4.0 release. 'ghost-buster' failed in 2 areas.
1. The setting in package.json was incorrectly set to `./core/index`. For the new Ghost, main needs to reference `index.js`.
2. Upon deploying the new Ghost to Modulus, images stored server side for the blog disappeared. I have not done much troubleshooting, but I have seen this behavior repeat across multiple deploys. Most consistent is the loss of the images in Ghost Settings for the blogger's profile and the blog logo.

**Comment by tzmanics** [comment]
Hi @BrianHoldsworth sorry for those errors you found in the 0.4.0 release and for the big delay in response. We aren't currently maintaining this repo so I'm going to close this issue for now. Once we figure out the next steps for `ghost-buster` we'll post an update on the repo.

Thanks for reaching out and feel free to re-open this issue if it's something you would like addressed sooner rather than later.
