### ISSUE TITLE
Blog "restarting" on Ghost 0.5.0

### ISSUE THREAD

**Issue by kalepail** [XervoIO/ghost-buster#8]
Ghost 0.5.0 added a quick-start setup screen when you first visit your dashboard for the first time. This is now showing up every time you deploy a change to the app. Ideally there would be a way to look for changes when you deploy to Modulus rather then moving everything over again. If I only change the .scss and .css files.. ideally I should be able to upload only those files that changed.

**Comment by tzmanics** [comment]
Hi @tyvdh sorry for the big delay in response. We aren't currently maintaining this repo so I'm going to close this issue for now. Once we figure out the next steps for `ghost-buster` we'll post an update on the repo.

Thanks for reaching out and feel free to re-open this issue if it's something you would like addressed sooner rather than later.
